# Generated by Django 2.2.2 on 2019-09-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('0', 'Politics'), ('1', 'Sports'), ('2', 'Health'), ('3', 'Business'), ('4', 'International'), ('5', 'Finance')], max_length=2),
        ),
    ]
