# Generated by Django 2.2.2 on 2019-10-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_remove_news_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_image', models.ImageField(upload_to='uploads')),
                ('title', models.CharField(max_length=270)),
                ('video_url', models.URLField(max_length=270)),
                ('upload_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Story',
        ),
    ]
