# Generated by Django 2.2.2 on 2019-11-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_news_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
        migrations.AddField(
            model_name='news',
            name='video_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads'),
        ),
        migrations.AddField(
            model_name='news',
            name='video_title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
