# Generated by Django 2.2.2 on 2019-11-13 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20191112_1537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='like',
            new_name='likes',
        ),
        migrations.AlterField(
            model_name='news',
            name='video_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
