# Generated by Django 2.2.2 on 2019-11-15 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_newsad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='tags',
        ),
    ]
