# Generated by Django 2.2.2 on 2019-11-25 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_auto_20191125_1000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='video_title',
        ),
        migrations.AlterField(
            model_name='news',
            name='video_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='news',
            name='video_url',
            field=models.URLField(max_length=270, null=True),
        ),
    ]
