# Generated by Django 2.2.2 on 2019-11-28 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0019_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='liked_news',
            field=models.BooleanField(default=False),
        ),
    ]
